### ISSUE TITLE
Setup ADB_PATH failed on windows platform.

### ISSUE THREAD

**Issue by codingbot47** [pikey8706/LogCatch#10]
I selected the sdk directory "D:/AndroidEnv/sdk" or "D:/AndroidEnv/sdk/platform-tools", but it still displays "Not confirmed". Did I miss any operation else?

**Comment by acdcjavier** [comment]
Hi
I have exactly the same issue, no fix for now

**Comment by pikey8706** [comment]
Hi
Selecting sdk directory worked for my env.
Need a moment after select directory to confirmed.
Selecting Platform directory is not working …  I may fix it at weekend.


2022年10月18日(火) 23:19 acdcjavier ***@***.***>:

**Comment by mitchcapper** [comment]
Small bug, I submitted a PR to fix this
